# Path: src\main\resources\application.yml
server:
  port: 80

# mysql data
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${DATA_BASE_NAME}?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
